// Generated by /from-issue on 2026-09-23 from Jira OR-2.
// Source: https://diegocortes15.atlassian.net/browse/OR-2
// Title: [OR][QA][Cart] Adding a product updates the cart badge and the cart contents
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import CatalogPage from '@pages/CatalogPage';
import ProductDetailPage from '@pages/ProductDetailPage';
import CartPage from '@pages/CartPage';

const PRODUCT = 'Sauce Labs Backpack (red)';
const BADGE_WINDOW_MS = 3_000; // measured 2026-09-23: a real add shows the badge 0.68–0.70 s after the tap

// Setup, not the subject: the cart tests below start from 6 units of PRODUCT.
async function addSixUnits(): Promise<void> {
  await CatalogPage.openProduct(PRODUCT);
  await ProductDetailPage.increaseQuantity(2);
  await ProductDetailPage.addToCart();
  await ProductDetailPage.addToCart();
}

describe('cart — no auth', () => {
  describe('Positive', () => {
    it('an empty cart shows no cart badge', async () => {
      // Absent from the view tree, not "0".
      await expect(CatalogPage.title).toHaveText('Products');
      await expect(CatalogPage.header.cartBadge).not.toExist();
    });

    it(`tapping the catalog card for ${PRODUCT} opens its detail screen`, async () => {
      await CatalogPage.openProduct(PRODUCT);

      await expect(ProductDetailPage.title).toHaveText(PRODUCT);
    });

    it('tapping increase quantity twice sets the quantity to 3', async () => {
      await CatalogPage.openProduct(PRODUCT);
      await ProductDetailPage.increaseQuantity(2);

      await expect(ProductDetailPage.quantity).toHaveText('3');
    });

    it('adding 3 units to the cart shows a cart badge of 3 @smoke', async () => {
      await CatalogPage.openProduct(PRODUCT);
      await ProductDetailPage.increaseQuantity(2);
      await ProductDetailPage.addToCart();

      await expect(ProductDetailPage.header.cartBadge).toHaveText('3');
    });

    it('adding 3 units twice shows a cart badge of 6, accumulating instead of replacing', async () => {
      await addSixUnits();

      await expect(ProductDetailPage.header.cartBadge).toHaveText('6');
    });

    // The colour is deliberately not asserted: the app exposes no colour value
    // to read, and Diego decided on 2026-09-23 not to verify it rather than
    // assert the presence of a swatch, which would prove nothing about colour.
    it('the cart lists one row for 6 units, with name, unit price and quantity @smoke', async () => {
      await addSixUnits();
      await CartPage.open();

      expect(await CartPage.getProductNames()).toEqual([PRODUCT]);
      expect(await CartPage.getUnitPrices()).toEqual(['$ 29.99']);
      expect(await CartPage.getQuantities()).toEqual(['6']);
    });

    it('the cart totals read "6 Items" and "$ 179.94" for 6 units', async () => {
      await addSixUnits();
      await CartPage.open();

      await expect(CartPage.totalItems).toHaveText('6 Items');
      await expect(CartPage.totalPrice).toHaveText('$ 179.94');
    });

    it('a cart holding a product is titled "My Cart"', async () => {
      await CatalogPage.openProduct(PRODUCT);
      await ProductDetailPage.addToCart();
      await CartPage.open();

      await expect(CartPage.title).toHaveText('My Cart');
    });

    it('a cart holding a product shows the Proceed To Checkout button', async () => {
      await CatalogPage.openProduct(PRODUCT);
      await ProductDetailPage.addToCart();
      await CartPage.open();

      await expect(CartPage.proceedToCheckoutButton).toBeDisplayed();
      await expect(CartPage.proceedToCheckoutButton).toHaveText('Proceed To Checkout');
    });
  });

  describe('Negative', () => {
    it('raising the quantity without tapping Add to cart puts nothing in the cart', async () => {
      await CatalogPage.openProduct(PRODUCT);
      await ProductDetailPage.increaseQuantity(2);
      // Positive signal first: the taps landed.
      await expect(ProductDetailPage.quantity).toHaveText('3');

      expect(await ProductDetailPage.header.cartBadgeAppearsWithin(BADGE_WINDOW_MS)).toBe(false);
    });
  });
});
