// Generated by /from-issue on 2026-09-23 from Jira OR-2.
// Source: https://diegocortes15.atlassian.net/browse/OR-2
// Title: [OR][QA][Cart] Adding a product updates the cart badge and the cart contents
// Augmented by: OR-6 (2026-09-28), OR-5 (2026-09-30)
// Ported to both platforms 2026-09-25 (ADR-0044).
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import CartPage from '@pages/CartPage';
import CatalogPage from '@pages/CatalogPage';
import ProductDetailPage from '@pages/ProductDetailPage';
import { RED_BACKPACK } from '@data/products';
import { itOn } from '@utils/platform-only';

const BADGE_WINDOW_MS = 3_000; // measured 2026-09-23: a real add shows the badge 0.68–0.70 s after the tap

// Setup, not the subject: the cart tests below start from 6 units of the product.
async function addSixUnits(): Promise<void> {
  await CatalogPage.openProduct(RED_BACKPACK.name);
  await ProductDetailPage.increaseQuantity(2);
  await ProductDetailPage.addToCart();
  await ProductDetailPage.addToCart();
}

// One tap on a cart row holding 6 units, in each direction (OR-5). The action
// is data, applied on one straight-line path.
const QUANTITY_CHANGES = [
  { change: 'decreasing', action: 'decreaseQuantity', units: 5 },
  { change: 'increasing', action: 'increaseQuantity', units: 7 },
] as const;

describe('cart — no auth', () => {
  describe('Positive', () => {
    it('an empty cart shows no cart badge', async () => {
      // Absent from the view tree on both platforms, not "0".
      await expect(CatalogPage.screen).toBeDisplayed();
      await expect(CatalogPage.navigation.cartBadge).not.toExist();
    });

    it('tapping a catalog card opens the detail screen of that product', async () => {
      await CatalogPage.openProduct(RED_BACKPACK.name);

      await expect(ProductDetailPage.title).toHaveText(RED_BACKPACK.name);
    });

    it('tapping increase quantity twice sets the quantity to 3', async () => {
      await CatalogPage.openProduct(RED_BACKPACK.name);
      await ProductDetailPage.increaseQuantity(2);

      await expect(ProductDetailPage.quantity).toHaveText('3');
    });

    it('adding 3 units to the cart shows a cart badge of 3 @smoke', async () => {
      await CatalogPage.openProduct(RED_BACKPACK.name);
      await ProductDetailPage.increaseQuantity(2);
      await ProductDetailPage.addToCart();

      await expect(ProductDetailPage.navigation.cartBadge).toHaveText('3');
    });

    it('adding 3 units twice shows a cart badge of 6, accumulating instead of replacing', async () => {
      await addSixUnits();

      await expect(ProductDetailPage.navigation.cartBadge).toHaveText('6');
    });

    // The colour is deliberately not asserted: Android exposes no colour value
    // to read, and Diego decided on 2026-09-23 not to verify it rather than
    // assert the presence of a swatch, which would prove nothing about colour.
    it('the cart lists one row for 6 units, with name, unit price and quantity @smoke', async () => {
      await addSixUnits();
      await CartPage.open();

      expect(await CartPage.getProductNames()).toEqual([RED_BACKPACK.name]);
      expect(await CartPage.getUnitPrices()).toEqual([RED_BACKPACK.unitPrice]);
      expect(await CartPage.getQuantities()).toEqual(['6']);
    });

    it('the cart totals read the number of items and the price for 6 units', async () => {
      await addSixUnits();
      await CartPage.open();

      await expect(CartPage.totalItems).toHaveText(RED_BACKPACK.totalItemsForSix);
      await expect(CartPage.totalPrice).toHaveText(RED_BACKPACK.totalPriceForSix);
    });

    it('a cart holding a product is titled "My Cart"', async () => {
      await addSixUnits();
      await CartPage.open();

      await expect(CartPage.title).toHaveText('My Cart');
    });

    it('a cart holding a product shows the Proceed To Checkout button', async () => {
      await addSixUnits();
      await CartPage.open();

      await expect(CartPage.proceedToCheckoutButton).toBeDisplayed();
    });

    // The empty cart is a separate view (OR-6). Each test asserts it is
    // DISPLAYED before its text: on iOS the view stays in the tree, hidden,
    // while the cart holds products, so text alone would pass on a full cart.
    it('an empty cart shows the title "No Items"', async () => {
      await CartPage.open();

      await expect(CartPage.emptyTitle).toBeDisplayed();
      await expect(CartPage.emptyTitle).toHaveText('No Items');
    });

    it('an empty cart shows the message that the cart is empty', async () => {
      await CartPage.open();

      await expect(CartPage.emptyMessage).toBeDisplayed();
      await expect(CartPage.emptyMessage).toHaveText(
        'Oh no! Your cart is empty. Fill it up with swag to complete your purchase.',
      );
    });

    it('an empty cart shows the Go Shopping button', async () => {
      await CartPage.open();

      await expect(CartPage.goShoppingButton).toBeDisplayed();
      await expect(CartPage.goShoppingButton).toHaveText('Go Shopping');
    });

    it('tapping Go Shopping on an empty cart returns to the catalog', async () => {
      await CartPage.open();
      await CartPage.goShopping();

      await expect(CatalogPage.screen).toBeDisplayed();
    });

    itOn(
      'android',
      'the iOS catalog heading is an element named "title" with no readable text',
      'tapping Go Shopping on an empty cart shows the catalog heading "Products"',
      async () => {
        await CartPage.open();
        await CartPage.goShopping();

        await expect(CatalogPage.heading).toHaveText('Products');
      },
    );

    // Absences of a settled view: open() has already arrived at the empty cart,
    // so nothing is still on its way and no bounded window is needed.
    it('an empty cart does not show the "My Cart" title', async () => {
      await CartPage.open();

      await expect(CartPage.title).not.toExist();
    });

    it('an empty cart does not show the totals', async () => {
      await CartPage.open();

      await expect(CartPage.totalItems).not.toExist();
      await expect(CartPage.totalPrice).not.toExist();
    });

    it('an empty cart does not show Proceed To Checkout', async () => {
      await CartPage.open();

      await expect(CartPage.proceedToCheckoutButton).not.toExist();
    });

    for (const { change, action, units } of QUANTITY_CHANGES) {
      it(`${change} a cart row of 6 units sets its quantity to ${units}`, async () => {
        await addSixUnits();
        await CartPage.open();
        await CartPage[action]();

        await expect(CartPage.quantity).toHaveText(String(units));
      });

      it(`${change} a cart row of 6 units makes the total read ${units} items`, async () => {
        await addSixUnits();
        await CartPage.open();
        await CartPage[action]();

        await expect(CartPage.totalItems).toHaveText(RED_BACKPACK.totalItemsFor(units));
      });

      it(`${change} a cart row of 6 units makes the total price ${units} times the unit price @smoke`, async () => {
        await addSixUnits();
        await CartPage.open();
        await CartPage[action]();

        await expect(CartPage.totalPrice).toHaveText(RED_BACKPACK.totalPriceFor(units));
      });
    }

    it('tapping Remove Item on a cart row of 6 units removes all of them and shows the empty cart', async () => {
      await addSixUnits();
      await CartPage.open();
      await CartPage.removeItem();

      await expect(CartPage.emptyTitle).toBeDisplayed();
    });

    it('removing the only product with Remove Item leaves no cart badge', async () => {
      await addSixUnits();
      await CartPage.open();
      await CartPage.removeItem();
      await expect(CartPage.emptyTitle).toBeDisplayed();

      // An absence: the badge must not linger or come back once the cart is empty.
      expect(await CartPage.navigation.cartBadgeAppearsWithin(BADGE_WINDOW_MS)).toBe(false);
    });

    it('decreasing a cart row from 6 to 5 units makes the cart badge read 5', async () => {
      await addSixUnits();
      await CartPage.open();
      await CartPage.decreaseQuantity();

      await expect(CartPage.navigation.cartBadge).toHaveText('5');
    });
  });

  describe('Negative', () => {
    it('raising the quantity without tapping Add to cart puts nothing in the cart', async () => {
      await CatalogPage.openProduct(RED_BACKPACK.name);
      await ProductDetailPage.increaseQuantity(2);

      expect(await ProductDetailPage.navigation.cartBadgeAppearsWithin(BADGE_WINDOW_MS)).toBe(
        false,
      );
    });
  });

  describe('Edge', () => {
    it('removing the last product with Remove Item shows the empty cart, titled "No Items" @smoke', async () => {
      await CatalogPage.openProduct(RED_BACKPACK.name);
      await ProductDetailPage.addToCart();
      await CartPage.open();
      await CartPage.removeItem();

      await expect(CartPage.emptyTitle).toBeDisplayed();
      await expect(CartPage.emptyTitle).toHaveText('No Items');
    });

    it('tapping decrease on a cart row of 1 unit removes the product and shows the empty cart', async () => {
      await CatalogPage.openProduct(RED_BACKPACK.name);
      await ProductDetailPage.addToCart();
      await CartPage.open();
      await CartPage.decreaseQuantity();

      await expect(CartPage.emptyTitle).toBeDisplayed();
    });
  });
});
