// Augmented by: OR-1 (2026-09-21)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import LoginPage from '@pages/LoginPage';
import CatalogPage from '@pages/CatalogPage';
import { itFails } from '@utils/expected-failure';

const NAVIGATION_WINDOW_MS = 5_000; // measured 2026-09-21: a sign-in reaches the catalog 1.2–1.35 s after the tap

// Hand-written in Phase 1 — deliberately NOT generated by /from-issue. Its only
// job is to prove the loop closes (emulator -> Appium -> WDIO -> assert) before
// a single line of any skill is adapted.
describe('Login — no auth', () => {
  describe('Positive', () => {
    it('bod@example.com logs in and lands on the catalog @smoke', async () => {
      await LoginPage.open();
      await expect(LoginPage.usernameInput).toBeDisplayed();

      await LoginPage.loginAs('bod@example.com', '10203040');

      await expect(CatalogPage.title).toBeDisplayed();
      await expect(CatalogPage.title).toHaveText('Products');
    });

    it('"Log In" in the menu opens the login screen with its username, password and Login controls', async () => {
      await LoginPage.open();

      await expect(LoginPage.usernameInput).toBeDisplayed();
      await expect(LoginPage.passwordInput).toBeDisplayed();
      await expect(LoginPage.loginButton).toBeDisplayed();
    });
  });

  describe('Negative', () => {
    const missingFields = [
      {
        input: 'an empty username',
        username: '',
        password: '10203040',
        error: 'usernameError',
        message: 'Username is required',
      },
      {
        input: 'an empty password',
        username: 'bod@example.com',
        password: '',
        error: 'passwordError',
        message: 'Enter Password',
      },
    ] as const;

    for (const { input, username, password, error, message } of missingFields) {
      it(`${input} is rejected with "${message}"`, async () => {
        await LoginPage.open();
        await LoginPage.loginAs(username, password);

        await expect(LoginPage[error]).toHaveText(message);
      });
    }

    it('alice@example.com is rejected as locked out @smoke', async () => {
      await LoginPage.open();
      await LoginPage.loginAs('alice@example.com', '10203040');

      await expect(LoginPage.passwordError).toHaveText('Sorry this user has been locked out.');
    });

    const wrongCredentials = [
      { input: 'a wrong password', username: 'bod@example.com', password: 'xxxxxxxx' },
      { input: 'a username with no account', username: 'nadie@example.com', password: '10203040' },
    ] as const;

    for (const { input, username, password } of wrongCredentials) {
      // OR-4 — the app signs in with any password and any unknown username.
      // Replace itFails with it when OR-4 is fixed; this test turning red is the notification.
      itFails('OR-4', `${input} does not open the catalog`, async () => {
        await LoginPage.open();
        await LoginPage.loginAs(username, password);

        expect(await CatalogPage.opensWithin(NAVIGATION_WINDOW_MS)).toBe(false);
      });
    }
  });

  describe('Edge', () => {
    it('the lockout message wins over a wrong password for alice@example.com', async () => {
      await LoginPage.open();
      await LoginPage.loginAs('alice@example.com', 'xxxxxxxx');

      await expect(LoginPage.passwordError).toHaveText('Sorry this user has been locked out.');
    });
  });
});
