import LoginPage from '@pages/LoginPage';
import CatalogPage from '@pages/CatalogPage';

// Hand-written in Phase 1 — deliberately NOT generated by /from-issue. Its only
// job is to prove the loop closes (emulator -> Appium -> WDIO -> assert) before
// a single line of any skill is adapted.
describe('Login — no auth', () => {
  describe('Positive', () => {
    it('bod@example.com logs in and lands on the catalog', async () => {
      await LoginPage.open();
      await expect(LoginPage.usernameInput).toBeDisplayed();

      await LoginPage.loginAs('bod@example.com', '10203040');

      await expect(CatalogPage.title).toBeDisplayed();
      await expect(CatalogPage.title).toHaveText('Products');
    });
  });
});
