// Generated by /scaffold-page-object on 2026-09-23.
// Tests using this Page Object are generated by /from-issue from Jira
// tickets. Manual edits are welcome — this file is not regenerated
// automatically.

import { Header } from '@components/Header';
import { step } from '@utils/step';

const PKG = 'com.saucelabs.mydemoapp.android:id';

class CartPage {
  readonly header = new Header();

  // "My Cart". No content-desc; resource-id productTV, which is also the
  // catalog's and the product detail's title id — assert its text, and never
  // use it as the arrival signal (see open()).
  get title() {
    return $(`id=${PKG}/productTV`);
  }

  // The list of rows. Its content-desc is unique to this screen (the catalog's
  // list, same resource-id productRV, says "Displays all products of catalog"),
  // which makes it the arrival signal.
  get productList() {
    return $('~Displays list of selected products');
  }

  // Totals: no content-desc, resource-id, 1 match each (verified 2026-09-23).
  get totalItems() {
    return $(`id=${PKG}/itemsTV`);
  }

  get totalPrice() {
    return $(`id=${PKG}/totalPriceTV`);
  }

  // Content-desc, 1 match. Its resource-id (cartBt) is the detail screen's
  // "Add to cart" button too.
  get proceedToCheckoutButton() {
    return $('~Confirms products for checkout');
  }

  /** Opens the cart from any screen that shows the header. */
  async open(): Promise<void> {
    await step('Open the cart', async () => {
      await this.header.openCart();
      await this.productList.waitForDisplayed();
    });
  }

  // Row queries are parallel arrays, one entry per row (component-detection.md:
  // uniform assertions across all rows, no per-row interaction yet). Rows carry
  // no content-desc on their text fields, so resource-id.
  async getProductNames(): Promise<string[]> {
    return $$(`id=${PKG}/titleTV`).map((e) => e.getText());
  }

  async getUnitPrices(): Promise<string[]> {
    return $$(`id=${PKG}/priceTV`).map((e) => e.getText());
  }

  async getQuantities(): Promise<string[]> {
    return $$(`id=${PKG}/noTV`).map((e) => e.getText());
  }

  /**
   * How many rows show a colour swatch. The swatch is an image whose
   * content-desc is generic ("Displays color of selected product"): the app
   * exposes no colour value to read, only that a swatch is there.
   */
  async getColorSwatchCount(): Promise<number> {
    return $$('~Displays color of selected product').length;
  }
}

// No fixtures in WebdriverIO: Page Objects are singletons.
export default new CartPage();
