// Generated by /scaffold-page-object on 2026-09-23, ported to both platforms
// 2026-09-25 (ADR-0044). Manual edits are welcome — this file is not
// regenerated automatically.

import { Navigation } from '@components/Navigation';
import { byPlatform } from '@utils/platform';
import { step } from '@utils/step';

const PKG = 'com.saucelabs.mydemoapp.android:id';

// iOS renders each cart row as a table cell whose StaticTexts are, in order:
// product name, unit price, "Color:", the colour, the quantity. Measured
// 2026-09-25; the positional chain is the only stable handle, because every
// one of those elements is named after the text it holds.
const IOS_ROW = '-ios class chain:**/XCUIElementTypeCell/XCUIElementTypeStaticText';

const EMPTY_MESSAGE = 'Oh no! Your cart is empty. Fill it up with swag to complete your purchase.';

class CartPage {
  readonly navigation = new Navigation();

  /**
   * The arrival signal. Android: the row list's content-desc, unique to this
   * screen (the catalog's list shares its resource-id). iOS: the screen
   * container. Never the title — see `title`.
   */
  get productList() {
    return $(byPlatform({ android: '~Displays list of selected products', ios: '~Cart-screen' }));
  }

  /**
   * "My Cart". Android: resource-id productTV, which is also the catalog's and
   * the product detail's title id — assert its text, never use it to detect
   * arrival. iOS: the heading's text is its accessibility id.
   */
  get title() {
    return $(byPlatform({ android: `id=${PKG}/productTV`, ios: '~My Cart' }));
  }

  /**
   * Totals. Android: resource-id, 1 match each. iOS: both are named after their
   * own text, so the predicate describes the SHAPE of that text. "No Items" —
   * the empty-cart view, which sits in the tree even when it is not on screen —
   * is excluded by requiring digits. The total price renders without a space
   * (`$179.94`) while a row's unit price has one (`$ 29.99`), which is what
   * keeps these two apart — hence `[^ ]+`, a pattern with no space in it.
   *
   * Measured 2026-09-25: a pattern containing `$` matched nothing at all
   * (`$` is the variable marker in a predicate), so the currency symbol is
   * never written into one. `[.]` avoids a backslash for the same reason.
   */
  get totalItems() {
    return $(
      byPlatform({
        android: `id=${PKG}/itemsTV`,
        ios: '-ios predicate string:type == "XCUIElementTypeStaticText" AND name MATCHES "[0-9]+ Items"',
      }),
    );
  }

  get totalPrice() {
    return $(
      byPlatform({
        android: `id=${PKG}/totalPriceTV`,
        ios: '-ios predicate string:type == "XCUIElementTypeStaticText" AND name MATCHES "[^ ]+[.][0-9][0-9]"',
      }),
    );
  }

  get proceedToCheckoutButton() {
    return $(byPlatform({ android: '~Confirms products for checkout', ios: '~ProceedToCheckout' }));
  }

  /**
   * One row's "Remove Item". Android: content-desc. iOS: a Button and a
   * StaticText are both named "Remove Item", so `~Remove Item` matches 2 —
   * the predicate asks for the Button. One match per row on each platform
   * (measured 2026-09-28): with several rows WebdriverIO would act on the
   * first, so a test that removes one of many needs a discriminator first.
   */
  get removeItemButton() {
    return $(
      byPlatform({
        android: '~Removes product from cart',
        ios: '-ios predicate string:type == "XCUIElementTypeButton" AND name == "Remove Item"',
      }),
    );
  }

  /**
   * One row's quantity controls. Android: content-desc (the product detail
   * screen reuses `~Increase item quantity`, but only one screen is in the tree
   * at a time). iOS: accessibility id. One match per row on each platform
   * (measured 2026-09-30); like `removeItemButton`, a test that changes one of
   * several rows needs a discriminator first.
   */
  get decreaseQuantityButton() {
    return $(byPlatform({ android: '~Decrease item quantity', ios: '~SubtractMinus Icons' }));
  }

  get increaseQuantityButton() {
    return $(byPlatform({ android: '~Increase item quantity', ios: '~AddPlus Icons' }));
  }

  /**
   * One row's quantity, for an auto-waiting assertion after changing it — the
   * same element `getQuantities()` reads across every row. Android: resource-id,
   * no content-desc. iOS: the quantity's name is its own number, so the row's
   * positional chain is the handle. One match per row (measured 2026-09-30).
   */
  get quantity() {
    return $(byPlatform({ android: `id=${PKG}/noTV`, ios: `${IOS_ROW}[5]` }));
  }

  // The empty cart is a separate view, not this screen with an empty list: it
  // holds a title, a message and a button, and none of the members above
  // (measured 2026-09-28, both platforms). On iOS its three elements stay in
  // the tree with visible="false" while the cart holds products, so assert them
  // with `toBeDisplayed` — `toHaveText` or `toExist` would pass on a full cart.

  /** "No Items". Android: resource-id, no content-desc. iOS: its text is its id. */
  get emptyTitle() {
    return $(byPlatform({ android: `id=${PKG}/noItemTitleTV`, ios: '~No Items' }));
  }

  /**
   * Android: no resource-id and no content-desc, so the text is the only handle
   * (UiSelector, exact match). iOS: the text is its accessibility id. Either
   * way a copy change breaks the locator, which is the honest cost of testing
   * a sentence.
   */
  get emptyMessage() {
    return $(
      byPlatform({
        android: `android=new UiSelector().text("${EMPTY_MESSAGE}")`,
        ios: `~${EMPTY_MESSAGE}`,
      }),
    );
  }

  /** iOS: `~GoShopping` is the Button; `~Go Shopping` is its StaticText label. */
  get goShoppingButton() {
    return $(byPlatform({ android: `id=${PKG}/shoppingBt`, ios: '~GoShopping' }));
  }

  /**
   * Opens the cart from any screen that shows the app's navigation, whether it
   * holds products or not. On Android the row list does not exist in an empty
   * cart, so arrival is the row list OR the empty view's title. On iOS the
   * row-list anchor is the screen container, present in both states.
   */
  async open(): Promise<void> {
    await step('Open the cart', async () => {
      await this.navigation.openCart();
      await driver.waitUntil(
        async () => (await this.productList.isDisplayed()) || (await this.emptyTitle.isDisplayed()),
        { timeoutMsg: 'The cart did not open: neither its rows nor its empty view appeared' },
      );
    });
  }

  async removeItem(): Promise<void> {
    await step('Remove the product from the cart', () => this.removeItemButton.click());
  }

  async decreaseQuantity(): Promise<void> {
    await step('Decrease the quantity in the cart', () => this.decreaseQuantityButton.click());
  }

  async increaseQuantity(): Promise<void> {
    await step('Increase the quantity in the cart', () => this.increaseQuantityButton.click());
  }

  async goShopping(): Promise<void> {
    await step('Go shopping from the empty cart', () => this.goShoppingButton.click());
  }

  // Row queries are parallel arrays, one entry per row (component-detection.md:
  // uniform assertions across all rows, no per-row interaction yet).
  async getProductNames(): Promise<string[]> {
    return $$(byPlatform({ android: `id=${PKG}/titleTV`, ios: `${IOS_ROW}[1]` })).map((e) =>
      e.getText(),
    );
  }

  async getUnitPrices(): Promise<string[]> {
    return $$(byPlatform({ android: `id=${PKG}/priceTV`, ios: `${IOS_ROW}[2]` })).map((e) =>
      e.getText(),
    );
  }

  async getQuantities(): Promise<string[]> {
    return $$(byPlatform({ android: `id=${PKG}/noTV`, ios: `${IOS_ROW}[5]` })).map((e) =>
      e.getText(),
    );
  }
}

// No fixtures in WebdriverIO: Page Objects are singletons.
export default new CartPage();
