// Generated by /scaffold-page-object on 2026-09-23, ported to both platforms
// 2026-09-25 (ADR-0044). Manual edits are welcome — this file is not
// regenerated automatically.

import { Navigation } from '@components/Navigation';
import { byPlatform } from '@utils/platform';
import { step } from '@utils/step';

const PKG = 'com.saucelabs.mydemoapp.android:id';

// iOS renders each cart row as a table cell whose StaticTexts are, in order:
// product name, unit price, "Color:", the colour, the quantity. Measured
// 2026-09-25; the positional chain is the only stable handle, because every
// one of those elements is named after the text it holds.
const IOS_ROW = '-ios class chain:**/XCUIElementTypeCell/XCUIElementTypeStaticText';

class CartPage {
  readonly navigation = new Navigation();

  /**
   * The arrival signal. Android: the row list's content-desc, unique to this
   * screen (the catalog's list shares its resource-id). iOS: the screen
   * container. Never the title — see `title`.
   */
  get productList() {
    return $(byPlatform({ android: '~Displays list of selected products', ios: '~Cart-screen' }));
  }

  /**
   * "My Cart". Android: resource-id productTV, which is also the catalog's and
   * the product detail's title id — assert its text, never use it to detect
   * arrival. iOS: the heading's text is its accessibility id.
   */
  get title() {
    return $(byPlatform({ android: `id=${PKG}/productTV`, ios: '~My Cart' }));
  }

  /**
   * Totals. Android: resource-id, 1 match each. iOS: both are named after their
   * own text, so the predicate describes the SHAPE of that text. "No Items" —
   * the empty-cart view, which sits in the tree even when it is not on screen —
   * is excluded by requiring digits. The total price renders without a space
   * (`$179.94`) while a row's unit price has one (`$ 29.99`), which is what
   * keeps these two apart — hence `[^ ]+`, a pattern with no space in it.
   *
   * Measured 2026-09-25: a pattern containing `$` matched nothing at all
   * (`$` is the variable marker in a predicate), so the currency symbol is
   * never written into one. `[.]` avoids a backslash for the same reason.
   */
  get totalItems() {
    return $(
      byPlatform({
        android: `id=${PKG}/itemsTV`,
        ios: '-ios predicate string:type == "XCUIElementTypeStaticText" AND name MATCHES "[0-9]+ Items"',
      }),
    );
  }

  get totalPrice() {
    return $(
      byPlatform({
        android: `id=${PKG}/totalPriceTV`,
        ios: '-ios predicate string:type == "XCUIElementTypeStaticText" AND name MATCHES "[^ ]+[.][0-9][0-9]"',
      }),
    );
  }

  get proceedToCheckoutButton() {
    return $(byPlatform({ android: '~Confirms products for checkout', ios: '~ProceedToCheckout' }));
  }

  /** Opens the cart from any screen that shows the app's navigation. */
  async open(): Promise<void> {
    await step('Open the cart', async () => {
      await this.navigation.openCart();
      await this.productList.waitForDisplayed();
    });
  }

  // Row queries are parallel arrays, one entry per row (component-detection.md:
  // uniform assertions across all rows, no per-row interaction yet).
  async getProductNames(): Promise<string[]> {
    return $$(byPlatform({ android: `id=${PKG}/titleTV`, ios: `${IOS_ROW}[1]` })).map((e) =>
      e.getText(),
    );
  }

  async getUnitPrices(): Promise<string[]> {
    return $$(byPlatform({ android: `id=${PKG}/priceTV`, ios: `${IOS_ROW}[2]` })).map((e) =>
      e.getText(),
    );
  }

  async getQuantities(): Promise<string[]> {
    return $$(byPlatform({ android: `id=${PKG}/noTV`, ios: `${IOS_ROW}[5]` })).map((e) =>
      e.getText(),
    );
  }
}

// No fixtures in WebdriverIO: Page Objects are singletons.
export default new CartPage();
