// Generated by /scaffold-page-object on 2026-09-23.
// Tests using this Page Object are generated by /from-issue from Jira
// tickets. Manual edits are welcome — this file is not regenerated
// automatically.

import { Header } from '@components/Header';
import { step } from '@utils/step';

const PKG = 'com.saucelabs.mydemoapp.android:id';

// Reached from the catalog with CatalogPage.openProduct(name). There is no
// open() here: which product is shown is decided on the catalog.
class ProductDetailPage {
  readonly header = new Header();

  // The product name. No content-desc, so resource-id — and the same id
  // (productTV) is the catalog's "Products" title and the cart's "My Cart".
  // Only one of those screens is in the tree at a time, but a wait for this
  // element to be displayed passes on the screen you came FROM: assert its
  // text, never its presence.
  get title() {
    return $(`id=${PKG}/productTV`);
  }

  // The quantity chosen before adding. No content-desc; resource-id, 1 match.
  get quantity() {
    return $(`id=${PKG}/noTV`);
  }

  // Content-desc values verified 2026-09-23: 1 match each on this screen.
  get increaseQuantityButton() {
    return $('~Increase item quantity');
  }

  get addToCartButton() {
    return $('~Tap to add product to cart');
  }

  async increaseQuantity(times = 1): Promise<void> {
    await step(`Increase the quantity ${times} time(s)`, async () => {
      for (let i = 0; i < times; i++) {
        await this.increaseQuantityButton.click();
      }
    });
  }

  async addToCart(): Promise<void> {
    await step('Add the product to the cart', () => this.addToCartButton.click());
  }
}

// No fixtures in WebdriverIO: Page Objects are singletons.
export default new ProductDetailPage();
